[server]
enableCORS = false
enableWebsocketCompression = false

[browser]
serverAddress = "franekdd-streamlittest-streamlit-app-6b1hv5.streamlit.app"

[theme]
primaryColor = "#E694FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#002651"
textColor = "#DCDCDC"
font = "sans-serif"
